# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    make
    echo 'Hello I am running make!!!!'
    ls
    ./primes_in_range 10 100
    ./primes_in_range 5 30
  displayName: 'make to build PrimesInRange'

- script: 
    echo 'Hello I am running make!!!!!'
  displayName: 'Fooling around'

- script:
    echo 'Running some basic test'
    ls
    ./primes_in_range 80 200
  displayName: 'Testing'